// apps/atlas-web/src/features/identity/presentation/LoginPage.tsx
import { useEffect, useState } from "react";
import type { RuntimeContext } from "../../../core/runtime-context";
import type { AuthSession, BenchUser } from "../domain/session";
import { syncFireweaveUser } from "../../../fireweave/fw-providers";
import {
  fetchUsers,
  loginAs,
  restoreSession,
} from "../application/auth-api";

export function LoginPage({
  ctx,
  onLoggedIn,
}: {
  ctx: RuntimeContext;
  onLoggedIn: (session: AuthSession) => void;
}) {
  const [users, setUsers] = useState<BenchUser[]>([]);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    void fetchUsers(ctx.apiBase)
      .then(setUsers)
      .catch((e) => setError(e instanceof Error ? e.message : String(e)));
  }, [ctx.apiBase]);

  return (
    <main className="shell">
      <div className="brand">
        <strong>fireweave</strong>
        <span>fixture · sign in</span>
      </div>
      <h1>Choose a user</h1>
      <p className="lede">
        Dummy bench users from the identity seed — pick one to complete login.
      </p>
      {error ? <pre className="probe bad">{error}</pre> : null}
      <ul className="user-list">
        {users.map((u) => (
          <li key={u.id}>
            <button
              type="button"
              disabled={busy}
              onClick={async () => {
                setBusy(true);
                setError("");
                try {
                  const session = await loginAs(ctx.apiBase, u.id);
                  void syncFireweaveUser(session.user.id, session.evaluationContext.properties);
                  onLoggedIn(session);
                } catch (e) {
                  setError(e instanceof Error ? e.message : String(e));
                } finally {
                  setBusy(false);
                }
              }}
            >
              <strong>{u.name}</strong>
              <span>{u.email}</span>
              <em>
                {u.org} · {u.plan} · {u.country}
              </em>
            </button>
          </li>
        ))}
      </ul>
    </main>
  );
}

export function useAuthGate(ctx: RuntimeContext) {
  const [session, setSession] = useState<AuthSession | null | undefined>(
    undefined,
  );

  useEffect(() => {
    if (!ctx.identityEnabled) {
      setSession(null);
      return;
    }
    void restoreSession(ctx.apiBase)
      .then(setSession)
      .catch(() => setSession(null));
  }, [ctx.apiBase, ctx.identityEnabled]);

  return { session, setSession, loading: session === undefined };
}

// apps/lantern-web/src/features/identity/presentation/LoginPage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { RuntimeContext } from "../../../core/runtime-context";
  import type { AuthSession, BenchUser } from "../domain/session";
  import { fetchUsers, loginAs } from "../application/auth-api";
  import { syncFireweaveUser } from "../../../../fireweave/fw-providers";

  let {
    ctx,
    onLoggedIn,
  }: {
    ctx: RuntimeContext;
    onLoggedIn: (session: AuthSession) => void;
  } = $props();

  let users = $state<BenchUser[]>([]);
  let error = $state("");
  let busy = $state(false);

  onMount(() => {
    void fetchUsers(ctx.apiBase)
      .then((list) => {
        users = list;
      })
      .catch((e) => {
        error = e instanceof Error ? e.message : String(e);
      });
  });

  async function pickUser(userId: string) {
    busy = true;
    error = "";
    try {
      const session = await loginAs(ctx.apiBase, userId);
      void syncFireweaveUser(session.user.id, session.evaluationContext.properties);
      onLoggedIn(session);
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      busy = false;
    }
  }
</script>

<main class="shell">
  <div class="brand">
    <strong>fireweave</strong>
    <span>fixture · sign in</span>
  </div>
  <h1>Choose a user</h1>
  <p class="lede">
    Dummy bench users from the identity seed — pick one to complete login.
  </p>
  {#if error}
    <pre class="probe bad">{error}</pre>
  {/if}
  <ul class="user-list">
    {#each users as u (u.id)}
      <li>
        <button type="button" disabled={busy} onclick={() => pickUser(u.id)}>
          <strong>{u.name}</strong>
          <span>{u.email}</span>
          <em>{u.org} · {u.plan} · {u.country}</em>
        </button>
      </li>
    {/each}
  </ul>
</main>
